### ISSUE TITLE
Question about Cogagent baseline implementations

### ISSUE THREAD

**Issue by zhiyuanhubj** [Berkeley-NLP/Agent-Eval-Refine#5]
Thanks for the solid work and detailed sharing. I have a question about the Cogagent results in this work.

In Figure 2, you mentioned that the action matching score of Cogagent in 120 tasks is 70.0% and released the records. However, I found there are 162 JSON files in ../AgentTrajectories/android/cogagent/, and they don't have the episode_id, so I can't match them with the original AITW data to calculate the action matching score. Could you please let us know which 120 tasks they are and share more details about the calculation of the 70% action matching score?

**Comment by Jiayi-Pan** [comment]
You can find the evaluated tasks [here](https://github.com/Berkeley-NLP/Agent-Eval-Refine/blob/main/exps/android_exp/assets/instructions.txt). Note that there are some redundant trajectories due to either the emulation system failing during execution or being outside the test instruction set.

Regarding the action matching score, as discussed in the paper, they aren't calculated on the 120 test tasks but are directly derived from the original paper. "Action matching scores are averaged across the subsets of AitW we sample from, as reported in Hong et al. (2023) and Zhang & Zhang (2023)."

**Comment by zhiyuanhubj** [comment]
Thanks for the prompt reply. I also noticed this annotation for the results. While, in the original paper of coagent, the average result of these four subsets is 72.73 (GoogleApp(74.95), Install( 78.86), WebShop(71.73), General(65.38)). And the overal performance in five subsets is 76.88. Hence, I am quite confused with the result in the paper (70.7%). Would you like to share more details?

**Comment by Jiayi-Pan** [comment]
As mentioned in the paper 
- "Action matching scores are averaged across the subsets of AitW we sample from". 
- "Note that we have excluded the Install and Single subsets. The install tasks require credit card information and are not safe to evaluate, while single-step tasks fall outside our focus on trajectory-level tasks."

GoogleApp(74.95), WebShop(71.73), General(65.38)) / 3 ~ 70.7

**Comment by zhiyuanhubj** [comment]
Got it. Thanks for your patient response.
